#!/bin/sh -e
does() { echo "$@"; "$@"; }
for f in *.[ch]
  do if [ $f -nt daety ]
    then
      does cc main.c client.c server.c socket.c -DVERS=0.1.6-`git rev-parse --short HEAD 2>/dev/null` -o daety -Wall -Wextra -pedantic
      break
  fi
done
case $1 in
  run)
    shift
    does exec ./daety "$@"
    ;;
  install)
    does cp ./daety ${PREFIX:-/usr/local}/bin/daety
    ;;
esac
